#!/bin/bash
#i3-msg "workspace 1;"
i3-msg "focus parent, focus parent, focus parent, focus parent, focus parent, focus parent, focus parent, focus parent, focus parent, focus parent, kill"

#i3-msg "append_layout $HOME/.i3/workspace-1.json"
#gnome-terminal --working-directory='dev' &
#gnome-terminal --working-directory='dev' &
#gnome-terminal --working-directory='dev' &

i3-msg "append_layout $HOME/.i3/workspace-urxvt.json"
i3-sensible-terminal -cd $HOME/dev &
i3-sensible-terminal -cd $HOME/dev &
i3-sensible-terminal -cd $HOME/dev &
